# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [2]:
x = np.random.randint(0, 20, size = (4, 7))
(x - x.min()) / (x.max() - x.min())

array([[1.        , 0.22222222, 0.61111111, 0.94444444, 0.27777778,
        0.61111111, 0.22222222],
       [0.94444444, 0.33333333, 0.88888889, 0.72222222, 0.77777778,
        1.        , 1.        ],
       [0.61111111, 0.33333333, 0.44444444, 0.16666667, 0.22222222,
        0.44444444, 0.94444444],
       [0.83333333, 0.72222222, 0.55555556, 0.11111111, 0.38888889,
        0.        , 0.27777778]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
a = np.random.randint(0, 10, size = (8, 10))
print(a)
b = np.sum(a, axis=1)
print(b)
np.argmin(b)

[[6 8 3 3 1 6 2 1 5 7]
 [0 5 7 3 3 8 9 7 7 4]
 [9 8 4 8 4 4 5 0 2 7]
 [6 9 4 4 7 5 4 0 5 7]
 [6 6 5 2 2 0 5 2 2 5]
 [8 6 0 8 1 3 8 3 1 6]
 [1 0 4 2 2 7 7 3 1 6]
 [5 5 5 4 2 4 7 7 8 7]]
[42 53 51 51 35 44 33 54]


6

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [4]:
import numpy as np
import random

In [5]:
arr = np.loadtxt(r'C:\Users\iyuli\OneDrive\Рабочий стол\ФИНАШКА\Технологии обработки данных\Тема 1\minutes_n_ingredients.csv', dtype=int, delimiter= ',', skiprows=1)
print(arr[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [6]:
print(arr)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


In [7]:
len(arr)

100000

2.Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
print(np.mean(arr[:, 1]), np.min(arr[:, 1]), np.max(arr[:, 1]), np.median(arr[:, 1]), sep='\n')

21601.00169
0
2147483647
40.0


In [9]:
print(np.mean(arr[:, 2]), np.min(arr[:, 2]), np.max(arr[:, 2]), np.median(arr[:, 2]), sep='\n')

9.05528
1
39
9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [10]:
quantile_value = int(np.quantile(arr[:, 1], 0.75))
print(quantile_value)
#arr[:, 1] = np.where(arr[:, 1] <= quantile_value, arr[:, 1], quantile_value)
arr[:, 1] = arr[:, 1].clip(max=quantile_value)
print(arr)

65
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [11]:
print(f'Количество рецептов, у которых продолжительность равна 0 = {np.count_nonzero(arr[:, 1] == 0)}')
arr[:, 1] = np.where(arr[:, 1] != 0, arr[:, 1], 1)

Количество рецептов, у которых продолжительность равна 0 = 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [12]:
'''
unique, counts = np.unique(arr[:, 0], return_counts=True)
for i in range(len(unique)):
    print(unique[i], counts[i])
'''

'\nunique, counts = np.unique(arr[:, 0], return_counts=True)\nfor i in range(len(unique)):\n    print(unique[i], counts[i])\n'

In [13]:
len(np.unique(arr[:, 0]))

100000

In [14]:
#np.unique(arr[:, 0])

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [15]:
unique, counts = np.unique(arr[:, 2], return_counts=True)
for i in range(len(unique)):
    print(unique[i], counts[i])

1 13
2 926
3 2895
4 5515
5 7913
6 9376
7 10628
8 10951
9 10585
10 9591
11 8297
12 6605
13 4997
14 3663
15 2595
16 1767
17 1246
18 790
19 573
20 376
21 217
22 161
23 105
24 69
25 50
26 28
27 16
28 16
29 12
30 12
31 3
32 1
33 2
34 1
35 3
37 1
39 1


In [16]:
len(np.unique(arr[:, 2]))

37

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [17]:
arr_5 = arr[arr[:, 2] <=5]
print(arr_5)
len(arr_5)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


17262

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [18]:
average = arr[:, 2] / arr[:, 1]
print(average)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]


In [19]:
np.max(average)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [20]:
arr_sort = arr[arr[:, 1].argsort()][::-1]
print(arr_sort)
print(np.mean(arr_sort[:100, 2]))

[[81993    65    14]
 [78310    65    12]
 [60218    65    14]
 ...
 [ 3492     1     7]
 [ 6975     1     8]
 [ 4896     1    14]]
9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [21]:
list_index = []
while len(list_index) < 10:
    i = random.randint(0, len(arr)-1)
    if i not in list_index:
        list_index.append(i)

print(arr[list_index, :])

[[328260     65      8]
 [524623     65     20]
 [  7159     25      8]
 [104162     65      7]
 [ 80243     65      9]
 [195343     20     15]
 [ 45603      5      6]
 [190570     55     16]
 [104445     30      7]
 [ 36617     15      3]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [22]:
mean = np.mean(arr[:, 2])
print(mean)
k = len(arr[arr[:, 2] <= mean])
print(k)
print(k / len(arr) * 100)

9.05528
58802
58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [23]:
arr_add = arr
dop_col = np.zeros(len(arr)).astype(int)
arr_add = np.c_[arr_add, dop_col]
arr_add[:, 3] = np.where((arr_add[:, 2] <=5) & (arr_add[:, 1] <= 20), 1, 0)
print(arr_add)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [24]:
k = len(arr_add[arr_add[:, 3] == 1])
print(k)
print(k / len(arr) * 100)

9552
9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [25]:
'''
#0 - короткие, 1 - от 10 до 20, 2 - от 20
arr_add = arr
dop_col = np.zeros(len(arr)).astype(int)
arr_add = np.c_[arr_add, dop_col]
arr_add[:, 3] = np.where((arr_add[:, 1] >= 10) & (arr_add[:, 1] < 20), 1, 0)
arr_add[:, 3] = np.where(arr_add[:, 1] >= 20, 2, arr_add[:, 3])
print(arr_add)
'''

'\n#0 - короткие, 1 - от 10 до 20, 2 - от 20\narr_add = arr\ndop_col = np.zeros(len(arr)).astype(int)\narr_add = np.c_[arr_add, dop_col]\narr_add[:, 3] = np.where((arr_add[:, 1] >= 10) & (arr_add[:, 1] < 20), 1, 0)\narr_add[:, 3] = np.where(arr_add[:, 1] >= 20, 2, arr_add[:, 3])\nprint(arr_add)\n'

In [26]:
#0 - короткие, 1 - от 10 до 20, 2 - от 2
arr_add = np.c_[arr_add, dop_col]
arr_add[:, 4] = np.where((arr_add[:, 1] >= 10) & (arr_add[:, 1] < 20), 1, 0)
arr_add[:, 4] = np.where(arr_add[:, 1] >= 20, 2, arr_add[:, 4])
print(arr_add)

[[127244     60     16      0      2]
 [ 23891     25      7      0      2]
 [ 94746     10      6      0      1]
 ...
 [498432     65     15      0      2]
 [370915      5      4      1      0]
 [ 81993     65     14      0      2]]


In [27]:
result = arr_add[:, [4, 0, 3]]
print(result)

[[     2 127244      0]
 [     2  23891      0]
 [     1  94746      0]
 ...
 [     2 498432      0]
 [     0 370915      1]
 [     2  81993      0]]


In [28]:
len(result[result[:, 0] == 0])

7588

In [29]:
len(result[result[:, 0] == 1])

12661

In [30]:
len(result[result[:, 0] == 2])

79751